/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("antlr")
    id("com.thougthworks.archguard.java-conventions")
}

dependencies {
    implementation("com.github.ajalt:clikt:2.5.0")
    implementation("org.eclipse.jgit:org.eclipse.jgit:5.3.1.201904271842-r")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.30")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.3.30")
    implementation("org.antlr:antlr4-runtime:4.7.2")
    implementation("org.slf4j:slf4j-jdk14:1.7.13")
    testImplementation("org.junit.jupiter:junit-jupiter:5.6.0")
}

group = "com.thougthworks.archguard.scanners"
description = "scan_git"


tasks.generateGrammarSource {
    maxHeapSize = "64m"
    arguments = arguments + listOf("-visitor", "-long-messages")
}

