ALTER TABLE system_configure
MODIFY COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE system_configure
MODIFY COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;