CREATE TABLE `Modules` (
  `id` char(36) CHARACTER SET utf8 NOT NULL,
  `name` char(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `packages` TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
